name: Push Docker image to ghcr.io

on:
  push:

jobs:
  build_and_publish:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v7
      - name: Build and push image for ${{ github.repository }}
        run: |
          declare -l repo=${{ github.repository }}
          declare -l org=${{ github.repository_owner }}
          docker login --username $org --password ${{ secrets.ACCESS_TOKEN }} ghcr.io 
          docker build . --tag ghcr.io/$repo:latest
          docker push ghcr.io/$repo:latest
